name: Playwright Tests

on:
  push:
  pull_request:
  
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium

      - name: Run tests
        run: npx playwright test tests/Mobile888.spec.js --project=chromium
        ## run: npx playwright test --project=chromium
        
      - name: Upload Test Results (Videos & Traces)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ runner.os }} 
          path: test-results/
          retention-days: 30

        ## ขอรันบน Website
      - name: Deploy Playwright Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always() # สำคัญมาก: ให้รันสเต็ปนี้เสมอแม้ว่าเทสต์จะพัง (Fail)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          keep_files: true # ถ้าอยากเก็บประวัติรีพอร์ตเก่าๆ ไว้
          destination_dir: latest-report # ตั้งชื่อโฟลเดอร์บนเว็บ
